version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 0.5G
          cpus: "0.25"

  webapp:
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 0.5G
          cpus: "0.25"
